export const PERSONAL_INFO = {
  name: 'Nahidujjaman Hridoy',
  title: 'Software Engineer',
  tagline: 'Creativity is my source code',
  bio: "I'm a Software Engineer with expertise in React, Next.js, Django, and AWS. I specialize in building full-stack applications with a focus on performance, security, and best practices. Having worked with Swiss, US, South Korean, and Bangladesh clients, I bring diverse experience in e-commerce, streaming platforms, ERP systems, and mobile applications.",
}

export const EXPERIENCE = [
  {
    role: 'Software Engineer',
    company: 'SELISE Bangladesh',
    period: 'Feb 2023 – Present',
    description:
      'Developing enterprise-grade web applications and scalable solutions for international clients. Focused on performance, security, best practices, and SEO across multiple projects using modern web technologies.',
  },
  {
    role: 'Senior Backend Developer',
    company: 'Potential',
    period: 'Apr 2024 – Aug 2025',
    description:
      'Led backend development for diverse applications including fitness trackers, e-commerce platforms, and video streaming services. Optimized API performance through caching and database tuning. Integrated payment gateways and social authentication. Worked extensively with Django REST Framework, PostgreSQL, Redis, and AWS cloud services.',
  },
  {
    role: 'Full Stack Developer',
    company: 'Nexis Ltd',
    period: 'Apr 2022 – Feb 2023',
    description:
      'Built full-stack applications including websites and HR Management Software with custom SSO systems. Integrated hardware devices like fingerprint attendance systems and automated document generation. Worked with Django, FastAPI, React, and cloud infrastructure.',
  },
  {
    role: 'Backend Developer',
    company: 'Techforing Ltd',
    period: 'Sep 2021 – Apr 2022',
    description:
      'Built backend systems and internal enterprise software. Developed company website and HR management & recruitment platforms.',
  },
]

export const SKILLS = {
  Frontend: [
    'ReactJS',
    'NextJS',
    'JavaScript',
    'TypeScript',
    'React Router',
    'zustand',
    'react-hook-form',
    'framer-motion',
    'Storyblok CMS',
    'Jest',
    'GraphQL',
  ],
  Backend: [
    'Python',
    'Django',
    'Django Rest Framework',
    'FastAPI',
    'Node.js',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Selenium',
    'Celery',
    'Firebase',
  ],
  'Tools & Practices': [
    'Docker',
    'Docker Compose',
    'AWS',
    'EC2',
    'ECS',
    'Fargate',
    'Lambda',
    'S3',
    'CloudFront',
    'SES',
    'Route53',
    'ALB',
    'Linux',
    'CI/CD',
    'Git',
    'Nginx',
  ],
}

export const CONTACT = {
  email: 'nahidujjamanhridoy@gmail.com',
  github: 'github.com/nhridoy',
  linkedin: 'linkedin.com/in/nahidujjaman-hridoy',
}

export const PROJECTS = [
  {
    id: 1,
    title: 'Zippsafe',
    description:
      'Smart locker room services, baggage transportation, documentation of valuables for personal, company, hospitals, restaurants and other industries in Asia, Europe and North America.',
    techStack: ['NextJS', 'TypeScript', 'Storyblok', 'Tailwind', 'shadcn', 'CI/CD', 'Netlify'],
    image: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&h=500&fit=crop',
    link: 'https://www.zippsafe.com/en',
    category: 'Website',
  },
  {
    id: 2,
    title: 'Kraak',
    description:
      'POS software, loyalty software, loyalty cards and payment solutions for restaurants - accompanies guests from reservation to order to payment.',
    techStack: ['NextJS', 'TypeScript', 'Storyblok', 'Tailwind', 'shadcn', 'CI/CD', 'Vercel'],
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=500&fit=crop',
    link: 'https://dev.kraak.ch/en/start',
    category: 'Website',
  },
  {
    id: 3,
    title: 'One Stop Service Solutions (OSSC)',
    description:
      'Government municipalities project for citizens to apply for certificates (citizen, character, birth/death, successor), trade licenses, and payments.',
    techStack: [
      'TypeScript',
      'NextJS',
      'GraphQL',
      'REST API',
      'Chakra UI',
      'MongoDB',
      'SSLCommerz',
    ],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=500&fit=crop',
    link: 'https://bhairab.ossc-bd.com/',
    category: 'Software Solution',
  },
  {
    id: 4,
    title: 'Sunrise Moments',
    description:
      "Loyalty platform for Sunrise's premium customers to purchase tickets for events like music and concerts at discounted prices.",
    techStack: [
      'TypeScript',
      'NextJS',
      'Storyblok',
      'REST API',
      'MongoDB',
      'Node.js',
      'Material UI',
    ],
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=500&fit=crop',
    link: 'https://www.sunrise.ch/en/moments',
    category: 'Ticketing Platform',
  },
  {
    id: 5,
    title: 'Nino',
    description: "E-commerce platform focusing on women's clothing and empowerment.",
    techStack: [
      'TypeScript',
      'NextJS',
      'ReactJS',
      'Python',
      'Django',
      'Django REST Framework',
      'Docker',
      'Docker Compose',
      'Dokploy',
      'Oracle',
      'SSLCommerz',
      'Tailwind',
      'shadcn',
      'Material UI',
    ],
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=500&fit=crop',
    link: 'https://ninobd.xyz/',
    category: 'E-Commerce',
  },
  {
    id: 6,
    title: 'BD Climax',
    description:
      'Multivendor e-commerce platform bringing different sellers and product categories under a single domain.',
    techStack: [
      'JavaScript',
      'ReactJS',
      'Django',
      'Django REST Framework',
      'Docker',
      'Docker Compose',
      'SSLCommerz',
      'Material UI',
    ],
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
    link: 'https://www.bdclimax.com/',
    category: 'Multivendor E-Commerce',
  },
  {
    id: 7,
    title: 'ULA',
    description:
      'Multivendor e-commerce platform bringing different sellers and product categories under a single domain.',
    techStack: [
      'JavaScript',
      'ReactJS',
      'Django',
      'Django REST Framework',
      'SSLCommerz',
      'Material UI',
    ],
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
    link: 'https://www.ula.com.bd/',
    category: 'Multivendor E-Commerce',
  },
  {
    id: 8,
    title: 'Online Streaming Service (OSS)',
    description:
      'Online streaming platform to search and watch movies and TV shows in multiple formats from multiple servers - aggregates content from the internet.',
    techStack: [
      'TypeScript',
      'NextJS',
      'Material UI',
      'Docker',
      'Docker Compose',
      'Dokploy',
      'Oracle',
    ],
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&h=500&fit=crop',
    link: 'https://oss.mailgrass.com/',
    category: 'Streaming Platform',
  },
  {
    id: 9,
    title: 'Al Quran',
    description:
      'Free Al Quran website where users can read or listen to Al Quran - fully PWA ready.',
    techStack: ['JavaScript', 'React', 'PWA', 'Netlify'],
    image: 'https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=800&h=500&fit=crop',
    link: 'https://elated-spence-963691.netlify.app/',
    category: 'Religious/Education',
  },
  {
    id: 10,
    title: 'Techforing',
    description: 'Cybersecurity company website providing various cybersecurity solutions.',
    techStack: ['Python', 'Django', 'Django Templating Language', 'AWS', 'EC2'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=500&fit=crop',
    link: 'https://techforing.com/',
    category: 'Website',
  },
  {
    id: 11,
    title: 'Elite4Print',
    description:
      'Complete ERP system for USA-based printing company - handles orders from website, processing, printing, delivery, tracking, and inventory management.',
    techStack: [
      'TypeScript',
      'NextJS',
      'Python',
      'Django',
      'Django REST Framework',
      'PostgreSQL',
      'Docker',
      'Docker Compose',
      'AWS',
      'EC2',
      'CI/CD',
    ],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=500&fit=crop',
    link: 'https://elite4print.com/',
    category: 'ERP Solution',
  },
  {
    id: 12,
    title: 'URL Shortener',
    description:
      'Free URL shortener platform - premium users get password protection, link expiry, OS-based and country-based redirection.',
    techStack: [
      'TypeScript',
      'NextJS',
      'Tailwind',
      'shadcn',
      'Python',
      'Django',
      'Django REST Framework',
      'Docker',
      'Docker Compose',
      'Dokploy',
      'Oracle',
    ],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=500&fit=crop',
    link: 'https://usf.mailgrass.com/',
    category: 'Utility Tool',
  },
  {
    id: 13,
    title: 'Dexulin',
    description:
      'Smart health & fitness tracking app - helps users track blood sugar, body composition, exercise, and meals with seamless device integration and daily missions.',
    techStack: [
      'Python',
      'Django',
      'Django REST Framework',
      'PostgreSQL',
      'Docker',
      'Docker Compose',
      'AWS',
      'EC2',
    ],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=500&fit=crop',
    link: 'https://potentialai.com/portfolio/dexulin',
    category: 'Android Application',
  },
  {
    id: 14,
    title: 'GTT Mobile',
    description:
      'Modern fitness app to track workouts, monitor daily activities, and motivate users through intuitive UI and data-driven insights.',
    techStack: [
      'Python',
      'Django',
      'Django REST Framework',
      'PostgreSQL',
      'Docker',
      'Docker Compose',
      'AWS',
      'EC2',
    ],
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=500&fit=crop',
    link: 'https://potentialai.com/portfolio/gtt-mobile-app',
    category: 'Android Application',
  },
  {
    id: 15,
    title: 'TOMO',
    description:
      'Tour & travel mobile app to connect explorers, plan gatherings, and make every journey memorable.',
    techStack: [
      'Python',
      'Django',
      'Django REST Framework',
      'PostgreSQL',
      'Docker',
      'Docker Compose',
      'AWS',
      'EC2',
    ],
    image: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&h=500&fit=crop',
    link: 'https://potentialai.com/portfolio/tomo-travel-together-explore-more',
    category: 'Android & iOS App',
  },
]
